# 这里端口改了的话，assets也要改
server:
  port: 2333
# 把localhost都改成127.0.0.1，username/password都改成自己的
spring:
  datasource:
    dboacc:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/dbo_acc?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
    dbochar:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/dbo_char?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
  # redis的ip，端口，密码
  redis:
    host: localhost
    port: 6379
    password:
  # 邮箱信息(账号是邮箱，密码是授权码)
  mail:
    host: smtp.qq.com
    username:
    password:
#  # 定时任务参数(不用动)
#  task:
#    scheduling:
#      pool:
#        size: 1
#      thread-name-prefix: reset_
#      shutdown:
#        await-termination: false
#        await-termination-period: 10s
# 注册参数
register:
  open: true # 是否开放注册(true/false)
  email-check: true # 是否开启邮箱验证(true/false)
  ip-max-num: 5 # ip注册最大数
  email-max-num: 5 # 邮箱注册最大数
# 登录验证码参数
login-code:
  open: false # 是否开启登录验证码（true/false）
  type: char # math是数字验证码，char是字母验证码

# 签到参数
signin:
  open: true # 是否开放签到(true/false)