server:
  port: 8080
spring:
  datasource:
    dboacc:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/dbo_page?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
    dbochar:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/dbo_char?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379

# 注册参数
register:
  open: true # 是否开放注册(true/false)
  email-check: true # 是否开启邮箱验证(true/false)
  ip-max-num: 5 # ip注册最大数
  email-max-num: 5 # 邮箱注册最大数
